Post::create([
  'title' => 'Postingan Pertama',
  'category_id' => 1,
  'slug' =>  'postingan-pertama',
  'excerpt' => '1Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem odio aliquam, aut qui magnam repellendus iure est! Quos totam eligendi aliquam perferendis repellendus nam debitis similique vero fugit sit excepturi libero laudantium ducimus obcaecati dicta ex culpa, ipsa alias. Sed, qui? Alias, recusandae id a magnam nulla quibusdam. Dolore officia quasi incidunt minima ipsum illo enim quisquam temporibus reprehenderit unde, asperiores,',
  'body' => '<p>1Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem odio aliquam, aut qui magnam repellendus iure est! Quos totam eligendi aliquam perferendis repellendus nam debitis similique vero fugit sit excepturi libero laudantium ducimus obcaecati dicta ex culpa, ipsa alias. Sed, qui? Alias, recusandae id a magnam nulla quibusdam. Dolore officia quasi incidunt minima ipsum illo enim quisquam temporibus reprehenderit unde, asperiores, cumque odit sapiente impedit deleniti voluptas soluta,</p><p>maxime odio alias! Fugit, cum nostrum cumque quae ipsa accusamus doloremque voluptate dignissimos autem! Culpa officia asperiores possimus officiis ratione. Mollitia excepturi impedit soluta ab, ut error earum labore eos officia, minus cupiditate veniam dicta sed,</p><p>velit laboriosam suscipit dignissimos. Suscipit voluptatum minus odio eligendi, esse omnis, eveniet ea accusantium expedita neque aperiam explicabo. Voluptas sunt, nihil rerum omnis in neque laboriosam expedita velit dignissimos blanditiis, labore magnam odio! Ex magnam laudantium cumque iure iusto ad! Obcaecati, reprehenderit beatae.</p><p>Impedit, quod quibusdam doloribus sed assumenda facere, accusantium nemo sint voluptates tenetur hic corporis aliquam ipsum tempore, nihil quisquam mollitia odio quidem fuga quae exercitationem error quaerat! Vel dolorem sit natus quae optio itaque odit deserunt? Commodi voluptatibus qui laborum voluptas,</p><p>inventore iste non dolores ratione fuga porro harum explicabo, omnis officiis id?</p>'
])
Post::create([
  'title' => 'Postingan Kedua',
  'category_id' => 2,
  'slug' =>  'postingan-kedua',
  'excerpt' => '2Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem odio aliquam, aut qui magnam repellendus iure est! Quos totam eligendi aliquam perferendis repellendus nam debitis similique vero fugit sit excepturi libero laudantium ducimus obcaecati dicta ex culpa, ipsa alias. Sed, qui? Alias, recusandae id a magnam nulla quibusdam. Dolore officia quasi incidunt minima ipsum illo enim quisquam temporibus reprehenderit unde, asperiores,',
  'body' => '<p>2Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem odio aliquam, aut qui magnam repellendus iure est! Quos totam eligendi aliquam perferendis repellendus nam debitis similique vero fugit sit excepturi libero laudantium ducimus obcaecati dicta ex culpa, ipsa alias. Sed, qui? Alias, recusandae id a magnam nulla quibusdam. Dolore officia quasi incidunt minima ipsum illo enim quisquam temporibus reprehenderit unde, asperiores, cumque odit sapiente impedit deleniti voluptas soluta,</p>'
])
Post::create([
  'title' => 'Postingan Ketiga',
  'category_id' => 1,
  'slug' =>  'postingan-ketiga',
  'excerpt' => '3Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem odio aliquam, aut qui magnam repellendus iure est! Quos totam eligendi aliquam perferendis repellendus nam debitis similique vero fugit sit excepturi libero laudantium ducimus obcaecati dicta ex culpa, ipsa alias. Sed, qui? Alias, recusandae id a magnam nulla quibusdam. Dolore officia quasi incidunt minima ipsum illo enim quisquam temporibus reprehenderit unde, asperiores,',
  'body' => '<p>3Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem odio aliquam, aut qui magnam repellendus iure est! Quos totam eligendi aliquam perferendis repellendus nam debitis similique vero fugit sit excepturi libero laudantium ducimus obcaecati dicta ex culpa, ipsa alias. Sed, qui? Alias, recusandae id a magnam nulla quibusdam. Dolore officia quasi incidunt minima ipsum illo enim quisquam temporibus reprehenderit unde, asperiores, cumque odit sapiente impedit deleniti voluptas soluta,</p><p>maxime odio alias! Fugit, cum nostrum cumque quae ipsa accusamus doloremque voluptate dignissimos autem! Culpa officia asperiores possimus officiis ratione. Mollitia excepturi impedit soluta ab, ut error earum labore eos officia, minus cupiditate veniam dicta sed,</p><p>velit laboriosam suscipit dignissimos. Suscipit voluptatum minus odio eligendi, esse omnis, eveniet ea accusantium expedita neque aperiam explicabo. Voluptas sunt, nihil rerum omnis in neque laboriosam expedita velit dignissimos blanditiis, labore magnam odio! Ex magnam laudantium cumque iure iusto ad! Obcaecati, reprehenderit beatae.</p><p>Impedit, quod quibusdam doloribus sed assumenda facere, accusantium nemo sint voluptates tenetur hic corporis aliquam ipsum tempore, nihil quisquam mollitia odio quidem fuga quae exercitationem error quaerat! Vel dolorem sit natus quae optio itaque odit deserunt? Commodi voluptatibus qui laborum voluptas,</p><p>inventore iste non dolores ratione fuga porro harum explicabo, omnis officiis id?</p>'
])
Post::create([
  'title' => 'Postingan Keempat',
  'category_id' => 1,
  'slug' =>  'postingan-keempat',
  'excerpt' => '4Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem odio aliquam, aut qui magnam repellendus iure est! Quos totam eligendi aliquam perferendis repellendus nam debitis similique vero fugit sit excepturi libero laudantium ducimus obcaecati dicta ex culpa, ipsa alias. Sed, qui? Alias, recusandae id a magnam nulla quibusdam. Dolore officia quasi incidunt minima ipsum illo enim quisquam temporibus reprehenderit unde, asperiores,',
  'body' => '<p>1Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem odio aliquam, aut qui magnam repellendus iure est! Quos totam eligendi aliquam perferendis repellendus nam debitis similique vero fugit sit excepturi libero laudantium ducimus obcaecati dicta ex culpa, ipsa alias. Sed, qui? Alias, recusandae id a magnam nulla quibusdam. Dolore officia quasi incidunt minima ipsum illo enim quisquam temporibus reprehenderit unde, asperiores, cumque odit sapiente impedit deleniti voluptas soluta,</p>'
])
Post::create([
  'title' => 'Postingan Kelima',
  'category_id' => 2,
  'slug' =>  'postingan-kelima',
  'excerpt' => '5Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem odio aliquam, aut qui magnam repellendus iure est! Quos totam eligendi aliquam perferendis repellendus nam debitis similique vero fugit sit excepturi libero laudantium ducimus obcaecati dicta ex culpa, ipsa alias. Sed, qui? Alias, recusandae id a magnam nulla quibusdam. Dolore officia quasi incidunt minima ipsum illo enim quisquam temporibus reprehenderit unde, asperiores,',
  'body' => '<p>5Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem odio aliquam, aut qui magnam repellendus iure est! Quos totam eligendi aliquam perferendis repellendus nam debitis similique vero fugit sit excepturi libero laudantium ducimus obcaecati dicta ex culpa, ipsa alias. Sed, qui? Alias, recusandae id a magnam nulla quibusdam. Dolore officia quasi incidunt minima ipsum illo enim quisquam temporibus reprehenderit unde, asperiores, cumque odit sapiente impedit deleniti voluptas soluta,</p><p>maxime odio alias! Fugit, cum nostrum cumque quae ipsa accusamus doloremque voluptate dignissimos autem! Culpa officia asperiores possimus officiis ratione. Mollitia excepturi impedit soluta ab, ut error earum labore eos officia, minus cupiditate veniam dicta sed,</p><p>velit laboriosam suscipit dignissimos. Suscipit voluptatum minus odio eligendi, esse omnis, eveniet ea accusantium expedita neque aperiam explicabo. Voluptas sunt, nihil rerum omnis in neque laboriosam expedita velit dignissimos blanditiis, labore magnam odio! Ex magnam laudantium cumque iure iusto ad! Obcaecati, reprehenderit beatae.</p><p>Impedit, quod quibusdam doloribus sed assumenda facere, accusantium nemo sint voluptates tenetur hic corporis aliquam ipsum tempore, nihil quisquam mollitia odio quidem fuga quae exercitationem error quaerat! Vel dolorem sit natus quae optio itaque odit deserunt? Commodi voluptatibus qui laborum voluptas,</p><p>inventore iste non dolores ratione fuga porro harum explicabo, omnis officiis id?</p>'
])
Post::create([
  'title' => 'Postingan Keenam',
  'category_id' => 1,
  'slug' =>  'postingan-kenam',
  'excerpt' => '6Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem odio aliquam, aut qui magnam repellendus iure est! Quos totam eligendi aliquam perferendis repellendus nam debitis similique vero fugit sit excepturi libero laudantium ducimus obcaecati dicta ex culpa, ipsa alias. Sed, qui? Alias, recusandae id a magnam nulla quibusdam. Dolore officia quasi incidunt minima ipsum illo enim quisquam temporibus reprehenderit unde, asperiores,',
  'body' => '<p>6Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem odio aliquam, aut qui magnam repellendus iure est! Quos totam eligendi aliquam perferendis repellendus nam debitis similique vero fugit sit excepturi libero laudantium ducimus obcaecati dicta ex culpa, ipsa alias. Sed, qui? Alias, recusandae id a magnam nulla quibusdam. Dolore officia quasi incidunt minima ipsum illo enim quisquam temporibus reprehenderit unde, asperiores, cumque odit sapiente impedit deleniti voluptas soluta,</p><p>maxime odio alias! Fugit, cum nostrum cumque quae ipsa accusamus doloremque voluptate dignissimos autem! Culpa officia asperiores possimus officiis ratione. Mollitia excepturi impedit soluta ab, ut error earum labore eos officia, minus cupiditate veniam dicta sed,</p><p>velit laboriosam suscipit dignissimos. Suscipit voluptatum minus odio eligendi, esse omnis, eveniet ea accusantium expedita neque aperiam explicabo. Voluptas sunt, nihil rerum omnis in neque laboriosam expedita velit dignissimos blanditiis, labore magnam odio! Ex magnam laudantium cumque iure iusto ad! Obcaecati, reprehenderit beatae.</p><p>Impedit, quod quibusdam doloribus sed assumenda facere, accusantium nemo sint voluptates tenetur hic corporis aliquam ipsum tempore, nihil quisquam mollitia odio quidem fuga quae exercitationem error quaerat! Vel dolorem sit natus quae optio itaque odit deserunt? Commodi voluptatibus qui laborum voluptas,</p><p>inventore iste non dolores ratione fuga porro harum explicabo, omnis officiis id?</p>'
])








